s = input("Enter your name :  ")
print("Name capitalize :", s.capitalize())
print("Your name have")
print("Find a in name = ",s.count('a'))
print("Find e in name = ",s.count('e'))
print("Find i in name = ",s.count('i'))
print("Find o in name = ",s.count('o'))
print("Find u in name = ",s.count('u'))
print("Find \ 'chai' \ in name = ",s.find('chai'))
print("Index \ 'som' \ in name = ",s.index('som'))
print("Replace chai with sak : ", s.replace('chai','sak'))